version: '3'

services:

  NotificationService:
    build: ./NotificationService
    image: microservices:notification
    ports:
      - "80:80"
    depends_on:
      - Library
      - ClientStorage

  Library:
    build: ./Library
    image: microservices:library
    ports:
      - "81:80"

  ClientStorage:
    build: ./ClientStorage
    image: microservices:clients
    ports:
      - "82:80"